# Generated by Django 4.0.3 on 2022-03-02 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_visitslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='agency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.agency'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estate',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
