# Generated by Django 4.0.2 on 2022-04-12 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_visitslot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='buyer',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='estate',
            old_name='date_dispo',
            new_name='date_available',
        ),
        migrations.RenameField(
            model_name='estateagent',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='estateagent',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='estateagent',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='emailAdress',
            new_name='email_address',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
    ]
