# Generated by Django 4.0.3 on 2022-03-02 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_estate_agency_alter_estate_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='estateagent',
            name='agency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.agency'),
            preserve_default=False,
        ),
    ]
